#common config
spring:
  profiles:    active: main
  # main:
    #내장형 WAS 미사용
    # web-application-type: none 
  redis:    sentinelYn: N
    host: 127.0.0.1 #127.0.0.1
    port: 6000 #6379
    password: tg1234
    
    #LIVE
    replica1:
      host: 127.0.0.1
      port: 6000
      password: tg1234
      
    vod:
      useYn: N  # VOD시 선택

server:
  port: 7070  # 웹서비스 포트, 스트리밍 모니터링용

#monitoring
management:
  endpoints:
    web:
      base-path: "/monitor"
      exposure:
        include: "*"        
        
#---: .yml 파일 구분
--- ### Local 환경 ###
spring:
  profiles: local
  thymeleaf:
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false 
  cache:
    jcache:      config: classpath:ehcache.xml
          
  security:
    user:      name: admin
      password: $2a$10$/SESwP3ukLsSnX4ZP35sJOE.Z/C7aYzyiaee3qJHP4PAOSP21UKmO
  jwt:
    secret: test1234#$

hls: # VOD 스트리밍 옵션
  segment:
    time: 5
    max: 20  # max > time
  encryptYn: N
  path:
    vod: D:/LIVE/TG_LIVE
  bandwidth:
    360p: 1280000
    480p: 2560000
    720p: 7680000
  resolution:
    low: 640x360
    mid: 852x480
    high: 1280x720
  type: advance # basic(high, low), advance(high, low, mid)
  adaptive: false #적응형 true, 일반 false
  
netty:
  http:
    useYn: Y
    streaming-mode: live
    port: 1936    
    ssl: 
      useYn: N
      path:
        key: D:/IDE/ssl/netty/privatekey.pem
        cert: D:/IDE/ssl/netty/netty.crt
  
  #사용안함
  rtsp:
    useYn: N
    port: 554
    ssl: 
      useYn: N
      path:
        key: D:/IDE/ssl/netty/privatekey.pem
        cert: D:/IDE/ssl/netty/netty.crt
  
logging:
  file:
    path: 
      main: D:/workspace/LMS_LITE_STREAM_1.0/logs/
          
--- ### 운영 환경 ###
spring:
  profiles: main
  thymeleaf:
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
   
  security:
    user:
      name: admin
      password: $2a$10$/SESwP3ukLsSnX4ZP35sJOE.Z/C7aYzyiaee3qJHP4PAOSP21UKmO
  jwt:
    secret: test1234#$

hls: # VOD 스트리밍 옵션
  segment:
    time: 5
    max: 20  # max > time
  encryptYn: N
  path:
    vod: D:/LIVE/TG_LIVE
  bandwidth:
    360p: 1280000
    480p: 2560000
    720p: 7680000
  resolution:
    low: 640x360
    mid: 852x480
    high: 1280x720
  type: advance # basic(high, low), advance(high, low, mid)
  adaptive: false #적응형 true, 일반 false
  
netty:
  http:
    useYn: Y
    streaming-mode: live
    port: 1936    
    ssl: 
      useYn: N
      path:
        key: D:/IDE/ssl/netty/privatekey.pem
        cert: D:/IDE/ssl/netty/netty.crt
  
  #사용안함
  rtsp:
    useYn: N
    port: 554
    ssl: 
      useYn: N
      path:
        key: D:/IDE/ssl/netty/privatekey.pem
        cert: D:/IDE/ssl/netty/netty.crt
  
logging:
  file:
    path: 
      main: /home/tigen235/demo-live/streaming/trunk/logs/
        